# Generated by Django 4.1.7 on 2023-03-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
