# Generated by Django 4.0.6 on 2022-08-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='verified',
        ),
        migrations.AddField(
            model_name='myuser',
            name='account_status',
            field=models.CharField(default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(default='STANDARD', max_length=100),
        ),
    ]
