# Generated by Django 4.0.6 on 2022-08-22 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_user_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='STANDARD', max_length=100)),
                ('account_status', models.CharField(default='ACTIVE', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('whatsapp_enabled_phone_number', models.CharField(max_length=15)),
                ('home_address', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'myusers',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
