# Generated by Django 4.1.4 on 2023-03-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_myuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
