# Generated by Django 4.1.7 on 2023-03-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image1',
        ),
        migrations.DeleteModel(
            name='Image10',
        ),
        migrations.DeleteModel(
            name='Image2',
        ),
        migrations.DeleteModel(
            name='Image20',
        ),
        migrations.DeleteModel(
            name='Image3',
        ),
        migrations.DeleteModel(
            name='Image4',
        ),
        migrations.DeleteModel(
            name='Image5',
        ),
        migrations.DeleteModel(
            name='Image8',
        ),
        migrations.DeleteModel(
            name='Image9',
        ),
    ]
