# Generated by Django 4.0.6 on 2022-08-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_image10_image11_image12_image13_image14_image15_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image11',
        ),
        migrations.DeleteModel(
            name='Image12',
        ),
        migrations.DeleteModel(
            name='Image13',
        ),
        migrations.DeleteModel(
            name='Image14',
        ),
        migrations.DeleteModel(
            name='Image15',
        ),
        migrations.DeleteModel(
            name='Image16',
        ),
        migrations.DeleteModel(
            name='Image17',
        ),
        migrations.DeleteModel(
            name='Image18',
        ),
        migrations.DeleteModel(
            name='Image19',
        ),
        migrations.DeleteModel(
            name='Image6',
        ),
        migrations.DeleteModel(
            name='Image7',
        ),
    ]
