# Generated by Django 4.1.4 on 2023-03-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cabservice_alter_cable_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableplan',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.cabservice'),
            preserve_default=False,
        ),
    ]
